//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadResultado
    {
        public int ActividadResultadoId { get; set; }
        public Nullable<int> Dias { get; set; }
        public string ResultadoId { get; set; }
        public string CampanaId { get; set; }
        public string ActividadResultanteId { get; set; }
        public string ActividadId { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
