//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadAdjunto
    {
        public string ActividadId { get; set; }
        public int AdjuntoId { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public string Enumeraciones { get; set; }
        public string Valor { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
