//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public string AlmacenId { get; set; }
        public string Nombre { get; set; }
        public string SucursalId { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public string Colonia { get; set; }
        public Nullable<bool> AutoAgregaMultiAlmacen { get; set; }
        public string CodigoPostal { get; set; }
        public string MunicipioId { get; set; }
        public string EstadoId { get; set; }
        public Nullable<bool> AlmacenExtranjero { get; set; }
        public string CtaContable { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<bool> AlmacenVirtual { get; set; }
        public string PaisId { get; set; }
        public string Clasificacion { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
