//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticuloExterno
    {
        public string ArticuloId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Unidad { get; set; }
        public Nullable<double> CostoInicial { get; set; }
        public Nullable<double> PorcentajeUtilidad { get; set; }
        public Nullable<double> PrecioPublico { get; set; }
        public string LineaId { get; set; }
        public string MonedaId { get; set; }
        public string EmpresaId { get; set; }
        public string ProveedorId { get; set; }
        public string PaisId { get; set; }
        public string FraccionId { get; set; }
        public string NombreExtranjero { get; set; }
        public Nullable<double> PesoExtranjero { get; set; }
        public string EmpaqueExtranjero { get; set; }
        public string EstatusId { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
