//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public string ArticuloId { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> Etiquetacion { get; set; }
        public string KitId { get; set; }
        public Nullable<double> FactorKit { get; set; }
        public string LineaId { get; set; }
        public Nullable<int> Origen { get; set; }
        public string Clasifica { get; set; }
        public string Clasifica1 { get; set; }
        public string Clasifica2 { get; set; }
        public string Clasifica3 { get; set; }
        public string Clasifica4 { get; set; }
        public string Clasifica5 { get; set; }
        public Nullable<double> Puntuacion { get; set; }
        public string Estatus { get; set; }
        public string ControAlmacen { get; set; }
        public string FabricanteId { get; set; }
        public Nullable<bool> AplicaDescuento { get; set; }
        public Nullable<bool> AplicaPrecioOficial { get; set; }
        public Nullable<bool> AplicaPrecioVariable { get; set; }
        public Nullable<bool> AplicaAnalisisAuto { get; set; }
        public Nullable<bool> AplicaForzaPublico { get; set; }
        public Nullable<bool> AplicaImpuestoIncluido { get; set; }
        public string ReferenciaEspecial { get; set; }
        public string EmpaqueEntrada { get; set; }
        public string EmpaqueIntermedio { get; set; }
        public string EmpaqueSalida { get; set; }
        public string EmpaqueTarima { get; set; }
        public Nullable<double> UnidadPaleta { get; set; }
        public Nullable<double> UnidadEntrada { get; set; }
        public Nullable<double> UnidadIntermedia { get; set; }
        public Nullable<double> UnidadSalida { get; set; }
        public Nullable<bool> UnidadVariable { get; set; }
        public Nullable<bool> UnidadCalculada { get; set; }
        public Nullable<int> ObligaCompra { get; set; }
        public Nullable<double> VolumenIni { get; set; }
        public Nullable<double> VolumenInt { get; set; }
        public Nullable<double> VolumenSal { get; set; }
        public Nullable<double> VolumenEmpTa { get; set; }
        public string PiezaArticuloId { get; set; }
        public Nullable<double> PiezaUnidad { get; set; }
        public string Sustituto { get; set; }
        public Nullable<bool> AplicaComision { get; set; }
        public Nullable<double> PorcComision { get; set; }
        public Nullable<double> PorcDescuento { get; set; }
        public Nullable<double> PorcImpuesto1 { get; set; }
        public Nullable<double> PorcImpuesto2 { get; set; }
        public string ImpuestoId { get; set; }
        public string UltimoProveedor { get; set; }
        public string DiaSurtido { get; set; }
        public Nullable<double> LimiteSeguridad { get; set; }
        public Nullable<double> LimiteMinimo { get; set; }
        public Nullable<double> LimiteMaximo { get; set; }
        public Nullable<bool> AplicaMaxMinporc { get; set; }
        public Nullable<double> Caducidad { get; set; }
        public string MonedaId { get; set; }
        public Nullable<double> CostoInicial { get; set; }
        public Nullable<double> MargenInicial { get; set; }
        public Nullable<double> PorcInicial { get; set; }
        public Nullable<double> DiferInicial { get; set; }
        public Nullable<double> CostoIntermedio { get; set; }
        public Nullable<double> MargenIntermedio { get; set; }
        public string DescripIntermedio { get; set; }
        public Nullable<double> DiferIntermedio { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<double> CostoNeto { get; set; }
        public Nullable<int> CosteoId { get; set; }
        public string MargenId { get; set; }
        public Nullable<bool> AplicaNivelSuelto { get; set; }
        public Nullable<double> PrecioMinimo { get; set; }
        public Nullable<double> PrecioMonedaAlterna { get; set; }
        public string Mensaje { get; set; }
        public string ArchivoScripting { get; set; }
        public string AlmacenIdDefault { get; set; }
        public string NombreIngles { get; set; }
        public string UnidadIngles { get; set; }
        public Nullable<double> PesoIngles { get; set; }
        public Nullable<int> NacionalExtranjero { get; set; }
        public string Observacion { get; set; }
        public string TipoFlete { get; set; }
        public string Adjuntos { get; set; }
        public string FleteIdEntrega { get; set; }
        public string ColectorIdSurtido { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public Nullable<int> MetodoCambioPrecio { get; set; }
        public Nullable<System.DateTime> FechaPrediccionSustituto { get; set; }
        public Nullable<int> obligaventa { get; set; }
        public Nullable<double> PrecioPaquete { get; set; }
        public string UltimoPedimento { get; set; }
        public Nullable<System.DateTime> FechaPedimento { get; set; }
    }
}
