//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraConfiguracionUsuario
    {
        public int BitacoraId { get; set; }
        public string UsuarioId { get; set; }
        public string AltaTipoNotificacion { get; set; }
        public string BajaTipoNotificacion { get; set; }
        public string CambioTipoNotificacion { get; set; }
        public string EjecucionTipoNotificacion { get; set; }
    }
}
