//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraConfiguracion
    {
        public int BitacoraConfigId { get; set; }
        public string Modificacion { get; set; }
        public string Afectado { get; set; }
        public string AltaTipoBitacora { get; set; }
        public string BajaTipoBitacora { get; set; }
        public string CambioTipoBitacora { get; set; }
        public string EjecucionTipoBitacora { get; set; }
    }
}
