//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambioPrecioDocumento
    {
        public string CambioPrecioDocumentoId { get; set; }
        public string Catalogo { get; set; }
        public string Registro { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public string UsuarioId { get; set; }
        public string EstacionId { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public Nullable<int> EstatusDocumento { get; set; }
        public Nullable<int> MetodoCambioPrecio { get; set; }
    }
}
