//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambioPrecioMovimiento
    {
        public string CambioPrecioDocumentoId { get; set; }
        public string ArticuloId { get; set; }
        public string EmpresaGrupoId { get; set; }
        public string ZonaId { get; set; }
        public string Tipo { get; set; }
        public string Criterio { get; set; }
        public Nullable<double> PublicoPre { get; set; }
        public Nullable<double> PublicoPost { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public Nullable<int> EstatusMovimiento { get; set; }
        public Nullable<double> CostoPre { get; set; }
        public Nullable<double> CostoPost { get; set; }
    }
}
