//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public string ClienteId { get; set; }
        public string TipoClienteId { get; set; }
        public string NombreComercial { get; set; }
        public string CodigoId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string RazonSocial { get; set; }
        public string RFC { get; set; }
        public string EstatusId { get; set; }
        public string MunicipioId { get; set; }
        public string EstadoId { get; set; }
        public string PaisId { get; set; }
        public string CURP { get; set; }
        public string SitioWeb { get; set; }
        public string ConceptoId { get; set; }
        public string EmpresaId { get; set; }
        public string ManejoCuenta { get; set; }
        public double Puntuacion { get; set; }
        public double FormaPago { get; set; }
        public bool RequiereFacturacion { get; set; }
        public bool DesglosaIva { get; set; }
        public bool RetieneIva { get; set; }
        public double SaldoActual { get; set; }
        public string NivelPublico { get; set; }
        public double PorceDescuento { get; set; }
        public double LimiteCredito { get; set; }
        public double SaldoAnterior { get; set; }
        public double CargosAcumula { get; set; }
        public double InteresAcumula { get; set; }
        public double AbonoAcumula { get; set; }
        public double DescuentoAcumula { get; set; }
        public double LimiteDescuento { get; set; }
        public double DiasCredito { get; set; }
        public double DiaVigencia { get; set; }
        public double VentaAnual { get; set; }
        public bool ObligaOrdenCompra { get; set; }
        public bool AutorizaCredito { get; set; }
        public bool RespetaMoneda { get; set; }
        public string MonedaId { get; set; }
        public double DiaDevolucion { get; set; }
        public string ObservacionCliente { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string CuentaContable { get; set; }
        public string VendedorId { get; set; }
        public string RevisionPago { get; set; }
        public string ExpedienteId { get; set; }
        public string AgenteAsignado { get; set; }
        public string SucursalDefault { get; set; }
        public string SubEmpresa { get; set; }
        public Nullable<System.DateTime> UltimaVenta { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string MetodoCalculo { get; set; }
        public string CampanaVentaId { get; set; }
        public string CampanaCobroId { get; set; }
        public string CampanaEntregaId { get; set; }
        public string ConceptoIdBanco { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public string ImagenCliente { get; set; }
        public string FechaRevision { get; set; }
        public string HoraRevision { get; set; }
        public string FechaPago { get; set; }
        public string HoraPago { get; set; }
        public string ImpuestoId { get; set; }
        public double LimiteFacturacion { get; set; }
        public bool RequierePago { get; set; }
        public Nullable<bool> ManejaAutorizacionEnEntrega { get; set; }
        public string Clasificacion { get; set; }
        public bool ObligaCommerciaId { get; set; }
    }
}
