//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteCFD
    {
        public string ClienteId { get; set; }
        public string CertificadoDigital { get; set; }
        public Nullable<bool> EmisionMail { get; set; }
        public Nullable<bool> EmisionImpresion { get; set; }
        public string Addendas { get; set; }
        public Nullable<bool> EnvioEncriptado { get; set; }
        public string EmailEnvio { get; set; }
        public Nullable<bool> ModoSilencioso { get; set; }
        public string TipoAddenda { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public string DigitosPagoPredeterminado { get; set; }
        public int MascaraEmail { get; set; }
        public bool MuestraObservacion { get; set; }
    }
}
