//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codigo
    {
        public string Origen { get; set; }
        public string AliasExterno { get; set; }
        public string ArticuloId { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<double> Unidad { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public string Tipo { get; set; }
    }
}
