//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunica
    {
        public int Comunico { get; set; }
        public string ComunicaId { get; set; }
        public string TablaId { get; set; }
        public string EmpresaId { get; set; }
        public string SucursalId { get; set; }
        public string AlmacenId { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> TiempoActualiza { get; set; }
        public Nullable<double> IntervaloActualiza { get; set; }
        public string IntervaloHora { get; set; }
        public string IntervaloDia { get; set; }
        public Nullable<double> NumeroRegistros { get; set; }
        public string CadenaConexion { get; set; }
        public string VistaRemota { get; set; }
        public string VistaLocal { get; set; }
        public Nullable<System.DateTime> UltimaActualizacion { get; set; }
        public Nullable<System.DateTime> UltimaEnvia { get; set; }
        public Nullable<System.DateTime> UltimaRecibe { get; set; }
        public Nullable<double> TipoActividad { get; set; }
        public Nullable<double> Sentido { get; set; }
        public string CampoRemoto { get; set; }
        public string CampoLocal { get; set; }
        public string OperacionSincro { get; set; }
        public string RutaRemota { get; set; }
        public string RutaLocal { get; set; }
        public string Llave { get; set; }
        public string Indice { get; set; }
        public string DirHttp { get; set; }
        public string DirFtp { get; set; }
        public string Triger { get; set; }
        public string UsuarioId { get; set; }
        public string Password { get; set; }
        public string Bitacora { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
