//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        public string ConceptoId { get; set; }
        public string Nombre { get; set; }
        public string OperacionId { get; set; }
        public string CtaContable { get; set; }
        public string CodOperacion { get; set; }
        public string Mascara { get; set; }
        public string Abreviatura { get; set; }
        public string TipoValidacion { get; set; }
        public string MetodoValidacion { get; set; }
        public string MonedaId { get; set; }
        public double Valor { get; set; }
        public double FactorUtilidad { get; set; }
        public bool IndicaCredito { get; set; }
        public double CargoAbono { get; set; }
        public double DiaCredito { get; set; }
        public bool DesglosaCaptura { get; set; }
        public bool DesglosaCierre { get; set; }
        public bool DesglosaCorte { get; set; }
        public string FamiliaId { get; set; }
        public string Enlace { get; set; }
        public string ClienteProveedor { get; set; }
        public string Manejo { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public Nullable<bool> ConsideraEfectivo { get; set; }
        public string MetodoPagoSat { get; set; }
        public bool ObligaCapturaDigitosPago { get; set; }
    }
}
