//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public string ConsultaId { get; set; }
        public string NombreConsulta { get; set; }
        public string Tabla { get; set; }
        public string Where { get; set; }
        public string OrderBy { get; set; }
        public string GroupBy { get; set; }
        public string SentenciaSql { get; set; }
        public Nullable<int> NumeroConsulta { get; set; }
        public string ParametrosRecibe { get; set; }
        public string ParametrosEnvia { get; set; }
        public string Llaves { get; set; }
        public string Imagen { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
