//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaCampo
    {
        public string ConsultaId { get; set; }
        public string NombreConsulta { get; set; }
        public string Campo { get; set; }
        public string NombreCampo { get; set; }
        public string TituloColumna { get; set; }
        public Nullable<int> Longitud { get; set; }
        public Nullable<int> Alineacion { get; set; }
        public string Tipo { get; set; }
        public string Mascara { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public Nullable<bool> Llave { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
