//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int ContactoId { get; set; }
        public string ClienteId { get; set; }
        public string TipoContactoId { get; set; }
        public string Descripcion { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string TelefonoPersonal { get; set; }
        public string Radio { get; set; }
        public string Extension { get; set; }
        public string Fax { get; set; }
        public string ExtensionFax { get; set; }
        public bool TonoAutomatico { get; set; }
        public string EMail { get; set; }
        public string MensajeriaInstantanea { get; set; }
        public string UsuarioWeb { get; set; }
        public string PasswordWeb { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string NumeroLetra { get; set; }
        public string Ciudad { get; set; }
        public string CodigoPostal { get; set; }
        public string ZonaId { get; set; }
        public string MunicipioId { get; set; }
        public string EstadoId { get; set; }
        public string PaisId { get; set; }
        public string FormaEnvio { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public double GISX { get; set; }
        public double GISY { get; set; }
        public Nullable<System.DateTime> FechaAniversario { get; set; }
        public string Llave { get; set; }
        public string RutaId { get; set; }
        public string Firma { get; set; }
        public string Imagen { get; set; }
        public string VendedorId { get; set; }
        public string NumeroInterior { get; set; }
    }
}
