//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costo
    {
        public string ArticuloId { get; set; }
        public string ZonaId { get; set; }
        public Nullable<double> CostoInicial { get; set; }
        public Nullable<double> Otros { get; set; }
        public Nullable<double> Flete { get; set; }
        public Nullable<double> CostoFinal { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
