//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costeo
    {
        public string EmpresaId { get; set; }
        public string SucursalId { get; set; }
        public string OperacionId { get; set; }
        public string Folio { get; set; }
        public int RenglonId { get; set; }
        public string AlmacenId { get; set; }
        public string ArticuloId { get; set; }
        public Nullable<double> Unidad { get; set; }
        public Nullable<double> FactorUnidad { get; set; }
        public Nullable<double> CostoFinal { get; set; }
        public Nullable<double> CostoNeto { get; set; }
        public Nullable<double> CostoCapa { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
        public Nullable<double> TipoCambio { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
