//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmDocumentoActividad
    {
        public string CrmDocumentoId { get; set; }
        public int Secuencia { get; set; }
        public string ActividadId { get; set; }
        public Nullable<int> ContactoId { get; set; }
        public string ResultadoId { get; set; }
        public string DocumentoId { get; set; }
        public string OperacionId { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public Nullable<int> Avance { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public string ActividadAdjuntoValor { get; set; }
        public Nullable<System.DateTime> FechaHoraInicial { get; set; }
        public Nullable<System.DateTime> FechaHoraFinal { get; set; }
        public string UsuarioId { get; set; }
        public string EmpleadoId { get; set; }
        public string Referencia { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    }
}
