//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrmDocumento
    {
        public string EmpresaId { get; set; }
        public string SucursalId { get; set; }
        public string CrmId { get; set; }
        public string ClienteId { get; set; }
        public string CampanaId { get; set; }
        public string UsuarioId { get; set; }
        public string Estatus { get; set; }
        public Nullable<double> Importe { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public string Referencia { get; set; }
    }
}
