//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public string EmpresaId { get; set; }
        public string SucursalId { get; set; }
        public string OperacionId { get; set; }
        public string Folio { get; set; }
        public string AlmacenId { get; set; }
        public string AlmacenTransf { get; set; }
        public string EstacionId { get; set; }
        public string ClienteProveedorId { get; set; }
        public Nullable<int> ContactoId { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<System.DateTime> FechaDocumento { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> TurnoId { get; set; }
        public Nullable<double> FormulaId { get; set; }
        public Nullable<double> SubTotalPublico { get; set; }
        public Nullable<double> SubTotalCosto { get; set; }
        public Nullable<double> ImpuestoTotal { get; set; }
        public Nullable<double> OfertaTotal { get; set; }
        public Nullable<double> DescuentoTotal { get; set; }
        public Nullable<double> DocumentoTotal { get; set; }
        public Nullable<double> FleteTotal { get; set; }
        public Nullable<double> IndirectoTotal { get; set; }
        public string UsuarioId { get; set; }
        public string EmpleadoId { get; set; }
        public string MonedaId { get; set; }
        public Nullable<double> TipoCambio { get; set; }
        public string MonedaId2 { get; set; }
        public Nullable<double> TipoCambio2 { get; set; }
        public string Estatus { get; set; }
        public string ConceptoId { get; set; }
        public Nullable<bool> IndicaImpresion { get; set; }
        public Nullable<bool> IndicaEnvio { get; set; }
        public Nullable<bool> IndicadorFinanciero { get; set; }
        public Nullable<bool> IndicadorInventario { get; set; }
        public Nullable<bool> IndicadorFleteIndirecto { get; set; }
        public string MetodoEnvio { get; set; }
        public string TipoDocumento { get; set; }
        public string TransaccionEstatus { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public Nullable<double> Impuesto2 { get; set; }
        public Nullable<double> Impuesto3 { get; set; }
    }
}
