//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoCFD
    {
        public string DocumentoId { get; set; }
        public Nullable<System.DateTime> FechaHoraEmision { get; set; }
        public string Timbre { get; set; }
        public string SelloSAT { get; set; }
        public string SelloPAC { get; set; }
        public decimal Importe { get; set; }
        public string EfectoComprobante { get; set; }
        public int ComprobanteValido { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public string VersionCFD { get; set; }
        public string Version { get; set; }
        public string NumCertificado { get; set; }
        public Nullable<System.DateTime> FechaXMLOriginal { get; set; }
        public string Ack { get; set; }
        public string UUIDCancelado { get; set; }
        public Nullable<System.DateTime> FechaCancelado { get; set; }
        public string NumCTAPago { get; set; }
        public string MetodoPagoSAT { get; set; }
        public string Referencia { get; set; }
        public int Consecutivo { get; set; }
        public Nullable<double> TipoCambio { get; set; }
        public string EmpresaId { get; set; }
        public string RFC { get; set; }
        public string Serie { get; set; }
        public Nullable<long> NumAprobacion { get; set; }
        public double Impuesto { get; set; }
        public Nullable<double> EstadoComprobante { get; set; }
        public string Pedimento { get; set; }
        public Nullable<System.DateTime> FechaPedimento { get; set; }
        public string Aduana { get; set; }
        public string ClienteId { get; set; }
    }
}
