//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoPagoElectronico
    {
        public string DocumentoId { get; set; }
        public string ConceptoId { get; set; }
        public int Secuencia { get; set; }
        public string Criptograma { get; set; }
        public Nullable<double> ImporteRetiro { get; set; }
        public Nullable<double> ImporteVenta { get; set; }
        public string AfiliacionId { get; set; }
        public byte[] NumeroTarjeta { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string BancoEmisor { get; set; }
        public string NumeroAprobacion { get; set; }
        public string SecuenciaTransaccion { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaHoraTransaccion { get; set; }
        public string NombreTarjetaHabiente { get; set; }
        public string Referencia { get; set; }
        public string ModoIngreso { get; set; }
        public Nullable<int> PuntosImporte { get; set; }
        public Nullable<int> PuntosNumero { get; set; }
        public Nullable<double> FactorPuntos { get; set; }
        public Nullable<int> PuntosAnteriores { get; set; }
        public Nullable<int> PuntosActuales { get; set; }
        public Nullable<System.DateTime> FechaPuntosExpira { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public Nullable<int> TipoTransaccion { get; set; }
        public string TipoTarjeta { get; set; }
        public string TipoOperacion { get; set; }
        public string MesAnoVencimiento { get; set; }
    }
}
