//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoPedimento
    {
        public string ArticuloId { get; set; }
        public string DocumentoId { get; set; }
        public string Lote { get; set; }
        public string Pedimento { get; set; }
        public double IGI { get; set; }
        public double DTA { get; set; }
        public int Cantidad { get; set; }
        public string Aduana { get; set; }
        public Nullable<System.DateTime> FechaPedimento { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
