//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public string EmpresaId { get; set; }
        public string AlmacenId { get; set; }
        public string Nombre { get; set; }
        public string ThemeWeb { get; set; }
        public string MonedaBase { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string NumeroLetra { get; set; }
        public string RazonSocial { get; set; }
        public string DirRazonSocial { get; set; }
        public string Ciudad { get; set; }
        public string CodigoPostal { get; set; }
        public string CalleFiscal { get; set; }
        public string ColoniaFiscal { get; set; }
        public string NumeroLetraFiscal { get; set; }
        public string CodigoPostalFiscal { get; set; }
        public string RFC { get; set; }
        public string HoraTurno { get; set; }
        public Nullable<decimal> NumeroTurnos { get; set; }
        public Nullable<decimal> HorarioLaboral { get; set; }
        public Nullable<decimal> HorarioJornada { get; set; }
        public string HoraSobrepedido { get; set; }
        public string Password { get; set; }
        public string Directorio { get; set; }
        public Nullable<decimal> NumeroCaja { get; set; }
        public Nullable<bool> Activa { get; set; }
        public string Observacion { get; set; }
        public string ObservacionVta { get; set; }
        public string Logo { get; set; }
        public string ClaveEmpresa { get; set; }
        public Nullable<decimal> NivelPrecio { get; set; }
        public Nullable<bool> ActivaCxC { get; set; }
        public Nullable<bool> ActivaCxP { get; set; }
        public string CtaContable { get; set; }
        public string ImpresorFactura { get; set; }
        public string ImpresorCotizacion { get; set; }
        public string UltimaFactura { get; set; }
        public Nullable<bool> AgregaRemision { get; set; }
        public string RutaFactura { get; set; }
        public string NotaCredito { get; set; }
        public Nullable<bool> GeneraSaldo { get; set; }
        public string FacturaDiaria { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string EstadoId { get; set; }
        public string PaisId { get; set; }
        public string CiudadFiscal { get; set; }
        public string EstadoFiscalId { get; set; }
        public string EmpresaGrupoId { get; set; }
        public string MunicipioId { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> EsDistribuidor { get; set; }
        public string ClienteId { get; set; }
        public string EmpresaProveedorId { get; set; }
        public string SucuralProveedorId { get; set; }
        public string ProveedorId { get; set; }
        public string RutaImagenReporte { get; set; }
        public Nullable<bool> UtilizaFacturaElectronica { get; set; }
        public string CodigoImportador { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public string UltimaFacturaCFD { get; set; }
        public string NotaCreditoCFD { get; set; }
        public string UrlKPI { get; set; }
    }
}
