//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaCFD
    {
        public string EmpresaId { get; set; }
        public string NoCertificado { get; set; }
        public string Certificado { get; set; }
        public string LlavePrivada { get; set; }
        public byte[] Password { get; set; }
        public string RutaFacturaXML { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public string CorreoNotificacion { get; set; }
        public Nullable<int> NumeroMinimoFolio { get; set; }
        public Nullable<int> EsquemaFacturacion { get; set; }
        public Nullable<bool> AgregaAddenda { get; set; }
        public string RegimenFiscal { get; set; }
        public Nullable<bool> UtilizaBOM { get; set; }
        public Nullable<int> ProveedorPAC { get; set; }
        public string ArchivoPFX { get; set; }
    }
}
