//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtiMov
    {
        public string etinumart { get; set; }
        public decimal eticanart { get; set; }
        public decimal etiprecio { get; set; }
        public decimal etiprecos { get; set; }
        public string etistatus { get; set; }
        public byte[] etifechor { get; set; }
        public string etirefere { get; set; }
        public string eticodope { get; set; }
    }
}
