//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtiquetaImprime
    {
        public string ArticuloId { get; set; }
        public string AlmacenId { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<double> CostoClave { get; set; }
        public Nullable<double> Publico { get; set; }
        public Nullable<System.DateTime> FechaImpresion { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<double> Unidad { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
