//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtArticulo
    {
        public string extnumart { get; set; }
        public string extnomart { get; set; }
        public decimal extunidad { get; set; }
        public decimal extcosini { get; set; }
        public decimal extprecos { get; set; }
        public decimal extutipub { get; set; }
        public decimal extprepub { get; set; }
        public string extnumlin { get; set; }
        public string extnummon { get; set; }
        public string extnumemp { get; set; }
        public string extnumusu { get; set; }
        public string extnumclt { get; set; }
        public string extnumpro { get; set; }
        public string extfabric { get; set; }
        public string extnombus { get; set; }
        public decimal extpesous { get; set; }
        public string extempaus { get; set; }
        public string extstatus { get; set; }
        public System.DateTime extfecini { get; set; }
    }
}
