//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Familia()
        {
            this.FamiliaArticuloes = new HashSet<FamiliaArticulo>();
        }
    
        public string FamiliaId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string TipoFamiliaId { get; set; }
        public Nullable<int> Grupo { get; set; }
        public string Imagen { get; set; }
        public string Descripcion { get; set; }
        public string FamiliaAsociadaId { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamiliaArticulo> FamiliaArticuloes { get; set; }
    }
}
