//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flete
    {
        public string FleteId { get; set; }
        public string ZonaId { get; set; }
        public string Tipo { get; set; }
        public string Nombre { get; set; }
        public string UrlWS { get; set; }
        public string UrlPaginaWeb { get; set; }
        public Nullable<double> ValorDinero { get; set; }
        public Nullable<double> ValorPorcentaje { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public string TipoSistema { get; set; }
        public Nullable<double> ImporteMinimo { get; set; }
        public Nullable<int> DiasUltimaVenta { get; set; }
        public Nullable<int> DiasEntregaAdicional { get; set; }
        public string ColectorId { get; set; }
        public string ActividadIdAdjunto { get; set; }
    }
}
