//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolioCFD
    {
        public string EmpresaId { get; set; }
        public string SucursalId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public string FolioInicial { get; set; }
        public string FolioFinal { get; set; }
        public int AnoAprobacion { get; set; }
        public int NumeroAprobacion { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public string NumeroSerialCertificado { get; set; }
        public string Tipo { get; set; }
    }
}
