//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fraccion
    {
        public string FraccionId { get; set; }
        public string PaisOrigen { get; set; }
        public Nullable<double> PorceArancel { get; set; }
        public Nullable<double> PorceAplicacion { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public string Excepcion { get; set; }
        public string Mensage { get; set; }
        public string PadronSectorialId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> CampoTA { get; set; }
        public Nullable<double> AdValoren { get; set; }
        public Nullable<double> Arancel { get; set; }
        public string Region { get; set; }
    }
}
