//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impresor
    {
        public string ImpresorId { get; set; }
        public string Path { get; set; }
        public string NombreWin { get; set; }
        public string Descripcion { get; set; }
        public string ComandoIni { get; set; }
        public string ComandoFin { get; set; }
        public string ComandoCajon { get; set; }
        public string ComandoCorte { get; set; }
        public string ComandoBarraOn { get; set; }
        public string ComandoBarraOff { get; set; }
    }
}
