//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpresorSistema
    {
        public string EmpresaId { get; set; }
        public string SucursalId { get; set; }
        public string ReporteId { get; set; }
        public string EstacionId { get; set; }
        public string Path { get; set; }
        public Nullable<bool> ImpresionLocal { get; set; }
        public string Clave { get; set; }
    }
}
