//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MargenPorcentaje
    {
        public string MargenId { get; set; }
        public string ZonaId { get; set; }
        public string EmpresaId { get; set; }
        public Nullable<double> PorceIni { get; set; }
        public Nullable<double> Nivel1 { get; set; }
        public Nullable<double> Nivel2 { get; set; }
        public Nullable<double> Nivel3 { get; set; }
        public Nullable<double> Nivel4 { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public double criterio1 { get; set; }
        public double criterio2 { get; set; }
        public double criterio3 { get; set; }
        public double criterio4 { get; set; }
    }
}
