//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuElemento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuElemento()
        {
            this.MenuUsuarios = new HashSet<MenuUsuario>();
        }
    
        public string MenuId { get; set; }
        public string Titulo { get; set; }
        public string Categoria { get; set; }
        public string Tipo { get; set; }
        public string Imagen { get; set; }
        public Nullable<double> Orden { get; set; }
        public string Elemento { get; set; }
        public string PermisoId { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuUsuario> MenuUsuarios { get; set; }
    }
}
