//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moneda
    {
        public string MonedaId { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> TipoCambio { get; set; }
        public Nullable<System.DateTime> UltimaModif { get; set; }
        public string Abreviatura { get; set; }
        public string WSTipoCambioOficial { get; set; }
        public string MonedaIdWs { get; set; }
        public string MonedaIdBanco { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
