//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public string EmpresaId { get; set; }
        public string SucursalId { get; set; }
        public string OperacionId { get; set; }
        public string Folio { get; set; }
        public int RenglonId { get; set; }
        public string ArticuloId { get; set; }
        public Nullable<double> Unidad { get; set; }
        public Nullable<double> FactorUnidad { get; set; }
        public string EmpaqueId { get; set; }
        public Nullable<double> UnidadPendiente { get; set; }
        public Nullable<double> UnidadBonificada { get; set; }
        public Nullable<double> InventarioActual { get; set; }
        public Nullable<double> PublicoInicial { get; set; }
        public Nullable<double> PublicoFinal { get; set; }
        public Nullable<double> CostoInicial { get; set; }
        public Nullable<double> CostoFinal { get; set; }
        public Nullable<double> CostoNeto { get; set; }
        public string ImpuestoId { get; set; }
        public Nullable<double> Impuesto { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<bool> IndicaCambioPrecio { get; set; }
        public Nullable<bool> IndicaInterfase { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public Nullable<double> Impuesto2 { get; set; }
        public Nullable<double> Impuesto3 { get; set; }
    }
}
