//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoPedimento
    {
        public string MovimientoId { get; set; }
        public Nullable<double> Unidades { get; set; }
        public string ArticuloId { get; set; }
        public Nullable<double> CostoFinal { get; set; }
        public Nullable<double> CostoNeto { get; set; }
        public Nullable<double> CostoInicial { get; set; }
        public string Pedimento { get; set; }
    }
}
