//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfertaVentaArticulo
    {
        public string OfertaVentaId { get; set; }
        public string ArticuloId { get; set; }
        public string EmpresaId { get; set; }
        public string ZonaId { get; set; }
        public string Criterio { get; set; }
        public Nullable<double> Publico { get; set; }
        public Nullable<double> Margen { get; set; }
        public string MonedaId { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraFin { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
