//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfertaCompra
    {
        public string OfertaCompraId { get; set; }
        public string Nombre { get; set; }
        public string ProveedorId { get; set; }
        public string TipoPolitica { get; set; }
        public string LineaId { get; set; }
        public string FamiliaId { get; set; }
        public string ArticuloIni { get; set; }
        public string ArticuloFin { get; set; }
        public Nullable<System.DateTime> FechaIni { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<double> UnidadIni { get; set; }
        public Nullable<double> UnidadFin { get; set; }
        public string ColectorId { get; set; }
        public string ClasificaProveedor { get; set; }
        public string Clasificacion { get; set; }
        public Nullable<double> Porcentaje { get; set; }
        public Nullable<double> Precio { get; set; }
        public string Mensaje { get; set; }
        public string AlmacenId { get; set; }
        public Nullable<double> MinimoCompra { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
