//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfertaVenta
    {
        public string OfertaVentaId { get; set; }
        public string EmpresaId { get; set; }
        public string SucursalId { get; set; }
        public string AlmacenId { get; set; }
        public string Nombre { get; set; }
        public string TipoAplicacion { get; set; }
        public string ClasificaCliente { get; set; }
        public string ArticuloIni { get; set; }
        public string ArticuloFin { get; set; }
        public string LineaId { get; set; }
        public string Clasificacion { get; set; }
        public string FamiliaId { get; set; }
        public Nullable<System.DateTime> FechaIni { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.DateTime> HoraIni { get; set; }
        public Nullable<System.DateTime> HoraFin { get; set; }
        public string DiaSemana { get; set; }
        public Nullable<double> Porcentaje { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> UnidadCompra { get; set; }
        public Nullable<double> UnidadOferta { get; set; }
        public Nullable<double> Puntuacion { get; set; }
        public Nullable<double> TipoPuntuacion { get; set; }
        public Nullable<double> MontoCompra { get; set; }
        public Nullable<double> Nivel { get; set; }
        public Nullable<double> AcumulaSustituye { get; set; }
        public Nullable<double> AplicaNivel { get; set; }
        public string Observacion { get; set; }
        public string Grafico { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public string ClasificacionCliente { get; set; }
        public string UsuarioId { get; set; }
        public Nullable<double> MontoMaximo { get; set; }
    }
}
