//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperacionColumna
    {
        public string OperacionId { get; set; }
        public string ColumnaId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Comportamiento { get; set; }
        public Nullable<int> AnchoColumna { get; set; }
        public Nullable<int> Alineacion { get; set; }
        public Nullable<int> Posicion { get; set; }
        public string Mascara { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
