//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcesoObjeto
    {
        public int ProcesoId { get; set; }
        public Nullable<int> CoorX { get; set; }
        public Nullable<int> CoorY { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Pendientes { get; set; }
        public string Texto { get; set; }
        public Nullable<int> IdentificadorInterno { get; set; }
        public string ConsultaID { get; set; }
        public string MenuElementoId { get; set; }
        public string CategoriaId { get; set; }
        public string TipoProceso { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string consultaidcount { get; set; }
        public string consultaidgrid { get; set; }
    }
}
