//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcesoImagen
    {
        public int ProcesoId { get; set; }
        public string ImagenAlmacenada { get; set; }
        public string layout { get; set; }
        public string tipoimagen { get; set; }
    }
}
