//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcesoLinea
    {
        public int procesoID { get; set; }
        public Nullable<int> x1 { get; set; }
        public Nullable<int> x2 { get; set; }
        public Nullable<int> y1 { get; set; }
        public Nullable<int> y2 { get; set; }
        public Nullable<bool> punteada { get; set; }
        public string color { get; set; }
        public Nullable<int> VoH { get; set; }
        public Nullable<int> puntoinicio { get; set; }
        public Nullable<int> puntofin { get; set; }
    }
}
