//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcesoProyectoNombre
    {
        public int ProcesoId { get; set; }
        public string NombreProyecto { get; set; }
        public string ExploradorId { get; set; }
        public Nullable<int> procesodefault { get; set; }
    }
}
