//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public string ProveedorId { get; set; }
        public string Nombre { get; set; }
        public string RazonSocial { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string TipoCompra { get; set; }
        public Nullable<double> MinimoCompra { get; set; }
        public string NumeroLetra { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string RFC { get; set; }
        public string Clasificacion { get; set; }
        public string CuentaContable { get; set; }
        public Nullable<double> SaldoAnual { get; set; }
        public Nullable<double> SaldoActual { get; set; }
        public string AttnPago { get; set; }
        public Nullable<double> PorceDescuento { get; set; }
        public string MonedaId { get; set; }
        public Nullable<double> DescFinal { get; set; }
        public Nullable<double> SurtidoNorma { get; set; }
        public Nullable<double> SurtidoUrgente { get; set; }
        public Nullable<double> SurtidoCritico { get; set; }
        public Nullable<double> DiaCaducidad { get; set; }
        public Nullable<double> DiaCredito { get; set; }
        public Nullable<double> LimiteCredito { get; set; }
        public string AttnCompras { get; set; }
        public string Observacion { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> UltimaModif { get; set; }
        public string HomePage { get; set; }
        public Nullable<double> FormaPago { get; set; }
        public Nullable<bool> DesglosaIva { get; set; }
        public Nullable<double> ImpuestoDefault { get; set; }
        public Nullable<bool> ObligaCapturaCosto { get; set; }
        public Nullable<double> PorcePedido { get; set; }
        public string MetodoCaptura { get; set; }
        public string AlmacenDefault { get; set; }
        public string EmpleadoId { get; set; }
        public Nullable<bool> Extranjero { get; set; }
        public string ClienteId { get; set; }
        public string PaisId { get; set; }
        public string EstadoId { get; set; }
        public string MunicipioId { get; set; }
        public string FormulaId { get; set; }
        public string Extension { get; set; }
        public string Notas { get; set; }
        public string ConceptoId { get; set; }
        public string EmpresaId { get; set; }
        public string Enviar { get; set; }
        public string Facturar { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
