//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Punto
    {
        public string EmpresaId { get; set; }
        public string SucursalId { get; set; }
        public string OperacionId { get; set; }
        public string Folio { get; set; }
        public string Referencia { get; set; }
        public string EmpresaGrupo { get; set; }
        public string ClienteId { get; set; }
        public int ContactoId { get; set; }
        public string ClienteIdPadre { get; set; }
        public double Puntos { get; set; }
        public double Factor { get; set; }
        public double TipoCambio { get; set; }
        public double Monto { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaDocumento { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
