//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public string ReporteId { get; set; }
        public string Alias { get; set; }
        public string UltimaVersion { get; set; }
        public string Ensamblado { get; set; }
        public string SalidaImpresion { get; set; }
        public Nullable<bool> Custom { get; set; }
        public string Clave { get; set; }
    }
}
