//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public string SucursalId { get; set; }
        public string Nombre { get; set; }
        public string EmpresaId { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string FaxTel { get; set; }
        public string Email { get; set; }
        public string UsuarioServer { get; set; }
        public string PasswordServer { get; set; }
        public string HomePage { get; set; }
        public string DirInbox { get; set; }
        public string DirOutbox { get; set; }
        public Nullable<bool> AgregaAutoAlm { get; set; }
        public Nullable<bool> AlmExtranjero { get; set; }
        public Nullable<bool> AlmVirtual { get; set; }
        public string Empleado { get; set; }
        public string CtaContable { get; set; }
        public string Zona { get; set; }
        public string Responsable { get; set; }
        public Nullable<int> NumeroAlmacen { get; set; }
        public string AlmacenId { get; set; }
        public string DirectorioDatos { get; set; }
        public string EmailWebAduana { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string MunicipioId { get; set; }
        public string Localidad { get; set; }
        public string Numero { get; set; }
        public string CodigoPostal { get; set; }
        public string PaisId { get; set; }
        public string EstadoId { get; set; }
        public string UrlWS { get; set; }
        public string Serie { get; set; }
        public string CriterioResurtido { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaServidor { get; set; }
        public string SerieDevolucion { get; set; }
        public Nullable<bool> ConexionGlobal { get; set; }
        public Nullable<int> NumeroSucursal { get; set; }
        public string UltimaFacturaCFD { get; set; }
        public string UltimaFactura { get; set; }
        public string NotaCreditoCFD { get; set; }
        public string NotaCredito { get; set; }
    }
}
