//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecla
    {
        public string TeclaId { get; set; }
        public int CodigoASCII { get; set; }
        public string Nombre { get; set; }
        public string FuncionTecla { get; set; }
        public string Sistema { get; set; }
        public int Tamano { get; set; }
        public int PosicionX { get; set; }
        public int PosicionY { get; set; }
        public int Color { get; set; }
        public int Estilo { get; set; }
        public string Imagen { get; set; }
        public string ArticuloId { get; set; }
        public double Unidades { get; set; }
        public string PestanaId { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
