//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransaccionEstatu
    {
        public string TransaccionId { get; set; }
        public string EstatusId { get; set; }
        public Nullable<System.DateTime> FechaHoraEstatus { get; set; }
        public Nullable<System.DateTime> FechaHoraEstatusVencimiento { get; set; }
        public string UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
    }
}
