//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedor
    {
        public string VendedorId { get; set; }
        public string Nombre { get; set; }
        public string NivelSeguridad { get; set; }
        public Nullable<double> PorceComision { get; set; }
        public string Fotografia { get; set; }
        public Nullable<double> Comision { get; set; }
        public string Puesto { get; set; }
        public string Clasificacion { get; set; }
        public string CtaContable { get; set; }
        public string NombreCta { get; set; }
        public Nullable<double> HrsJornada { get; set; }
        public Nullable<System.DateTime> FechaModif { get; set; }
        public Nullable<decimal> VtaAcumulada { get; set; }
        public Nullable<decimal> MermaAcumulada { get; set; }
        public Nullable<decimal> LimiteMerma { get; set; }
        public Nullable<System.DateTime> UltBorradoAcumulado { get; set; }
        public Nullable<System.DateTime> venultche { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public Nullable<int> CriterioMaximoPrecio { get; set; }
        public Nullable<double> PorceTopeUtilidad { get; set; }
    }
}
