//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTrompo
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaPerdida
    {
        public string VentaPerdidaId { get; set; }
        public string EmpresaId { get; set; }
        public string SucursalId { get; set; }
        public string ArticuloId { get; set; }
        public string Nombre { get; set; }
        public string Marca { get; set; }
        public Nullable<double> Unidad { get; set; }
        public string EmpaqueId { get; set; }
        public Nullable<double> Precio { get; set; }
        public string Tipo { get; set; }
        public string PatronBusqueda { get; set; }
        public string Observacion { get; set; }
        public string UsuarioId { get; set; }
        public string ClienteId { get; set; }
        public string OperacionId { get; set; }
        public string DocumentoId { get; set; }
        public string EmailNotifica { get; set; }
        public Nullable<System.DateTime> FechaHoraRegistro { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<System.DateTime> FechaHoraServer { get; set; }
        public string AlmacenId { get; set; }
    }
}
